# Generated by Django 2.2.17 on 2021-05-25 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not provided', max_length=14, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('image', models.URLField(default='not provided', max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=74)),
                ('closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_listing', to=settings.AUTH_USER_MODEL)),
                ('watchlist_user', models.ManyToManyField(blank=True, related_name='watchlist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
